language: java
jdk:
  - oraclejdk8

sudo: required
services:
  - docker

cache:
  directories:
    - '$HOME/.gradle'

before_install:
  - docker pull confluentinc/cp-zookeeper:latest
  - docker pull confluentinc/cp-kafka:latest

install:
  - ./gradlew build